apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: kubeops-demo
data:
  APP_NAME: kubeops-backend
  APP_VERSION: "1.0.0"
  APP_ENV: local-kubernetes

  # Future database configuration.
  # These values are intentionally empty for now.
  DB_HOST: ""
  DB_PORT: "3306"
  DB_NAME: ""
  DB_USER: ""