apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kubeops-demo
type: Opaque
stringData:
  DEMO_API_KEY: kubernetes-demo-key

  # Future database password.
  # Empty for now because we do not use a database yet.
  DB_PASSWORD: ""